/**
 * This file contains all of the action constants.
 */

export const GET_PROJECT_LIST_START = 'GET_PROJECT_LIST_START';
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS';
export const GET_PROJECT_LIST_ERROR = 'GET_PROJECT_LIST_ERROR';
export const SAVE_PROJECT_START = 'SAVE_PROJECT_START';
export const SAVE_PROJECT_SUCCESS = 'SAVE_PROJECT_SUCCESS';
export const SAVE_PROJECT_ERROR = 'SAVE_PROJECT_ERROR';
export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';
export const GET_PROJECT_DETAILS_START = 'GET_PROJECT_DETAILS_START';
export const GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS';
export const GET_PROJECT_DETAILS_ERROR = 'GET_PROJECT_DETAILS_ERROR';
export const SET_PROJECT_DATA = 'SET_PROJECT_DATA';

export const SAVE_SPRINT_START = 'SAVE_SPRINT_START';
export const SAVE_SPRINT_SUCCESS = 'SAVE_SPRINT_SUCCESS';
export const SAVE_SPRINT_ERROR = 'SAVE_SPRINT_ERROR';
export const GET_ALL_SPRINT_LIST_START = 'GET_ALL_SPRINT_LIST_START';
export const GET_ALL_SPRINT_LIST_SUCCESS = 'GET_ALL_SPRINT_LIST_SUCCESS';
export const GET_ALL_SPRINT_LIST_ERROR = 'GET_ALL_SPRINT_LIST_ERROR';
export const UPDATE_SPRINT_START = 'UPDATE_SPRINT_START';
export const UPDATE_SPRINT_SUCCESS = 'UPDATE_SPRINT_SUCCESS';
export const UPDATE_SPRINT_ERROR = 'UPDATE_SPRINT_ERROR';
export const GET_SPRINT_DETAILS_START = 'GET_SPRINT_DETAILS_START';
export const GET_SPRINT_DETAILS_SUCCESS = 'GET_SPRINT_DETAILS_SUCCESS';
export const GET_SPRINT_DETAILS_ERROR = 'GET_SPRINT_DETAILS_ERROR';
export const SET_SPRINT_DATA = 'SET_SPRINT_DATA';

export const SAVE_USER_STORIES_START = 'SAVE_USER_STORIES_START';
export const SAVE_USER_STORIES_SUCCESS = 'SAVE_USER_STORIES_SUCCESS';
export const SAVE_USER_STORIES_ERROR = 'SAVE_USER_STORIES_ERROR';
export const ADD_SUCCESS_CRITERIA = 'ADD_SUCCESS_CRITERIA';
export const REMOVE_SUCCESS_CRITERIA = 'REMOVE_SUCCESS_CRITERIA';
export const CLEAR_SUCCESS_CRITERIA = 'CLEAR_SUCCESS_CRITERIA';
export const GET_USER_STORIES_START = 'GET_USER_STORIES_START';
export const GET_USER_STORIES_SUCCESS = 'GET_USER_STORIES_SUCCESS';
export const GET_USER_STORIES_ERROR = 'GET_USER_STORIES_ERROR';
export const SET_USER_STORIES_DATA = 'SET_USER_STORIES_DATA';

export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const CLEAR_PROJECT_DATA = 'CLEAR_PROJECT_DATA';
export const CLEAR_SPRINT_DATA = 'CLEAR_SPRINT_DATA';
export const CLEAR_USER_STORIES_DATA = 'CLEAR_USER_STORIES_DATA';

export const UPDATE_USERS_CREDITS_START = 'UPDATE_USERS_CREDITS_START';
export const UPDATE_USERS_CREDITS_SUCCESS = 'UPDATE_USERS_CREDITS_SUCCESS';
export const UPDATE_USERS_CREDITS_ERROR = 'UPDATE_USERS_CREDITS_ERROR';

export const UPDATE_USERS_ROLE_START = 'UPDATE_USERS_ROLE_START';
export const UPDATE_USERS_ROLE_SUCCESS = 'UPDATE_USERS_ROLE_SUCCESS';
export const UPDATE_USERS_ROLE_ERROR = 'UPDATE_USERS_ROLE_ERROR';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const SAVE_CREATE_USER_SUCCESS = 'SAVE_CREATE_USER_SUCCESS';
export const SAVE_CREATE_USER_START = 'SAVE_CREATE_USER_START';
export const CREATE_USER_SAVE_ERROR = 'CREATE_USER_SAVE_ERROR';

export const GET_DISCOUNT_MANAGEMENT_START = 'GET_DISCOUNT_MANAGEMENT_START';
export const GET_DISCOUNT_MANAGEMENT_SUCCESS = 'GET_DISCOUNT_MANAGEMENT_SUCCESS';
export const GET_DISCOUNT_MANAGEMENT_ERROR = 'GET_DISCOUNT_MANAGEMENT_ERROR';

export const ADD_DISCOUNT_MANAGEMENT_START = 'ADD_DISCOUNT_MANAGEMENT_START';
export const ADD_DISCOUNT_MANAGEMENT_SUCCESS = 'ADD_DISCOUNT_MANAGEMENT_SUCCESS';
export const ADD_DISCOUNT_MANAGEMENT_ERROR = 'ADD_DISCOUNT_MANAGEMENT_ERROR';

export const DELETE_DISCOUNT_MANAGEMENT_START = 'DELETE_DISCOUNT_MANAGEMENT_START';
export const DELETE_DISCOUNT_MANAGEMENT_SUCCESS = 'DELETE_DISCOUNT_MANAGEMENT_SUCCESS';
export const DELETE_DISCOUNT_MANAGEMENT_ERROR = 'DELETE_DISCOUNT_MANAGEMENT_ERROR';

export const MOVE_USER_STORY_TO_ANOTHER_SPRINT_START = 'MOVE_USER_STORY_TO_ANOTHER_SPRINT_START';
export const MOVE_USER_STORY_TO_ANOTHER_SPRINT_SUCCESS = 'MOVE_USER_STORY_TO_ANOTHER_SPRINT_SUCCESS';
export const MOVE_USER_STORY_TO_ANOTHER_SPRINT_ERROR = 'MOVE_USER_STORY_TO_ANOTHER_SPRINT_ERROR';

export const UPDATE_USER_STORY_START = 'UPDATE_USER_STORY_START';
export const UPDATE_USER_STORY_SUCCESS = 'UPDATE_USER_STORY_SUCCESS';
export const UPDATE_USER_STORY_ERROR = 'UPDATE_USER_STORY_ERROR';

export const GET_ONE_SPRINT_LIST_START = 'GET_ONE_SPRINT_LIST_START';
export const GET_ONE_SPRINT_LIST_SUCCESS = 'GET_ONE_SPRINT_LIST_SUCCESS';
export const GET_ONE_SPRINT_LIST_ERROR = 'GET_ONE_SPRINT_LIST_ERROR';

export const GET_CREDIT_START = 'GET_CREDIT_START';
export const GET_CREDIT_SUCCESS = 'GET_CREDIT_SUCCESS';
export const GET_CREDIT_ERROR = 'GET_CREDIT_ERROR';

export const GET_CREDIT_HISTORY_START = 'GET_CREDIT_HISTORY_START';
export const GET_CREDIT_HISTORY_SUCCESS = 'GET_CREDIT_HISTORY_SUCCESS';
export const GET_CREDIT_HISTORY_ERROR = 'GET_CREDIT_HISTORY_ERROR';

export const GET_CREDIT_BY_PROJECT_START = 'GET_CREDIT_BY_PROJECT_START';
export const GET_CREDIT_BY_PROJECT_SUCCESS = 'GET_CREDIT_BY_PROJECT_SUCCESS';
export const GET_CREDIT_BY_PROJECT_ERROR = 'GET_CREDIT_BY_PROJECT_ERROR';

export const GET_PACKAGE_START = 'GET_PACKAGE_START';
export const GET_PACKAGE_SUCCESS = 'GET_PACKAGE_SUCCESS';
export const GET_PACKAGE_ERROR = 'GET_PACKAGE_ERROR';

export const APPLY_VOUCHER_START = 'APPLY_VOUCHER_START';
export const APPLY_VOUCHER_SUCCESS = 'APPLY_VOUCHER_SUCCESS';
export const APPLY_VOUCHER_ERROR = 'APPLY_VOUCHER_ERROR';

export const DELETE_USER_STORY_START = 'DELETE_USER_STORY_START';
export const DELETE_USER_STORY_SUCCESS = 'DELETE_USER_STORY_SUCCESS';
export const DELETE_USER_STORY_ERROR = 'DELETE_USER_STORY_ERROR';

export const PAYMENT_START = 'PAYMENT_START';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';

export const GET_ONE_USER_STORY_START = 'GET_ONE_USER_STORY_START';
export const GET_ONE_USER_STORY_SUCCESS = 'GET_ONE_USER_STORY_SUCCESS';
export const GET_ONE_USER_STORY_ERROR = 'GET_ONE_USER_STORY_ERROR';


export const MOVE_UNSELECTED_STORIES_ANOTHER_SPRINT_ERROR = 'MOVE_UNSELECTED_STORIES_ANOTHER_SPRINT_ERROR';
export const NOT_ENOUGH_CREDITS_ERROR = 'NOT_ENOUGH_CREDITS_ERROR';

export const RESERVE_CREDITS_START = 'RESERVE_CREDITS_START';
export const RESERVE_CREDITS_SUCCESS = 'RESERVE_CREDITS_SUCCESS';
export const RESERVE_CREDITS_ERROR = 'RESERVE_CREDITS_ERROR';

export const DEDUCT_CREDITS_START = 'DEDUCT_CREDITS_START';
export const DEDUCT_CREDITS_SUCCESS = 'DEDUCT_CREDITS_SUCCESS';
export const DEDUCT_CREDITS_ERROR = 'DEDUCT_CREDITS_ERROR';

export const GET_BID_PROJECT_SPRINTS = "GET_BID_PROJECT_SPRINTS";
export const GET_BID_PROJECT_SPRINTS_SUCCESS = "GET_BID_PROJECT_SPRINTS_SUCCESS";
export const GET_BID_PROJECT_SPRINTS_ERROR = "GET_BID_PROJECT_SPRINTS_ERROR";

export const GET_BID_PROJECT_SPRINTS_USER_STORIES = "GET_BID_PROJECT_SPRINTS_USER_STORIES";
export const GET_BID_PROJECT_SPRINTS_USER_STORIES_SUCCESS = "GET_BID_PROJECT_SPRINTS_USER_STORIES_SUCCESS";
export const GET_BID_PROJECT_SPRINTS_USER_STORIES_ERROR = "GET_BID_PROJECT_SPRINTS_USER_STORIES_ERROR";

export const GET_STORY_DETAILS = "GET_STORY_DETAILS";
export const GET_STORY_DETAILS_SUCCESS = "GET_STORY_DETAILS_SUCCESS";

export const UPDATE_EXISTING_BID = "UPDATE_EXISTING_BID";
export const UPDATE_EXISTING_BID_SUCCESS = "UPDATE_EXISTING_BID_SUCCESS";