/**
 * This file contains all of the action constants.
 */

export const SAVE_USER_STORIES_START = 'SAVE_USER_STORIES_START';
export const SAVE_USER_STORIES_SUCCESS = 'SAVE_USER_STORIES_SUCCESS';
export const SAVE_USER_STORIES_ERROR = 'SAVE_USER_STORIES_ERROR';
export const GET_USER_STORIES_START = 'GET_USER_STORIES_START';
export const GET_USER_STORIES_SUCCESS = 'GET_USER_STORIES_SUCCESS';
export const GET_USER_STORIES_ERROR = 'GET_USER_STORIES_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';

export const APPROVED_USER_STORY = 'APPROVED_USER_STORY';
export const REJECT_USER_STORY = 'REJECT_USER_STORY';